language: node_js
node_js:
  - "iojs"
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: dfcO1BFxXBut8nPoiP5JvBUlYJJk8S03hgdlSMkwgiPE4EpL5bof211da/RbtoVcTDZRnOBE2FLZXyTYX3p3j0dHl2JZOD33W5VvoRLHfmYbQC041WviGwX8XUlgoCC8ZGKueJFbQAaapWpfQ4LE6MFxkuKvNFCidCHfbTyhYQ9keAdtvqM0P96EuIuSvrI3HIHjztzc/Q3BSi8RB5mWMkEtWqTf3LNo0rHDAUhXliY41e8lE/m/eYvu3UhlyOz4MPVyKd2EpvyyjiI1uo2BNeSV1B7MZ7r9lk4MWn30TK4LxWyK06IjFg0FR2NzHR5O9IcrB4Af1pJHGD9COM2AnYl4bWGMtPajUAeumTYMqn38K+fDipzl2o45nKzHr+ig4VBky1UUe31KXFDLWOb2XiOAXPVYJ4sOaoFWS+RiqzOqsvegNHbrOuytOneimKNF93AtodpJh+PJo4++DR5VMORrtFxYPLF8dZMenfbpUiIbQbchqHMzywMHQq5IaVpEYKQHRX52eYhSHHBiLyHMA3ukCQqkHA1hRvsMsUG78jUAPB8UlE9SUIsK+8Jp5LooI3BxHhHYl4wHL07KGIziyy+TXsX7waO0Bxavf/nwamHnVJRTMKNxDdPySNx0Os3zqGqJjRNZXaM3Olg9RyTJYkPpg/k9Z63UrzNgZ3tyl7k=
  app: lychee-crisp-25683
